datasetDomain: knowledge
quantumName: Wardley Book
userConsumptionMode: operational
version: 1.0.0
status: test
uuid: 53581432-6c55-4ba2-a65f-72344a91553a
description:
  purpose: Views built on top of the seller tables.
  limitations: Data based on seller perspective, no buyer information
  usage: Predict sales over time
productDl: wardley-map@myorg.com
sourcePlatform: owulveryck's blog
project: Sample Data Contract and Rag
datasetName: wardley_book
kind: DataContract
apiVersion: v2.2.2
type: objects
driver: httpfs:parquet
driverVersion: 1.0.0
database: https://blog.owulveryck.info/assets/sampledata
dataset:
  - table: wardleybook.parquet
    description: The book from simon wardley, chunked
    authoritativeDefinitions:
      - url: https://blog.owulveryck.info/2024/06/12/the-future-of-data-management-an-enabler-to-ai-devlopment-a-basic-illustration-with-rag-open-standards-and-data-contracts.html
        type: explanation
    dataGranularity: Chunking manually according to paragraphs
    columns:
      - column: chunk_id
        isPrimaryKey: true
        logicalType: int
        physicalType: INT32
        isNullable: false
      - column: content
        businessName: Part of the book
        logicalType: string
        physicalType: BYTE_ARRAY
        description: A chunk of the book in markdown
